### PR TITLE
Updated svelte workflow to use yarn

### PR DESCRIPTION
**Pull request by Vithop**
Added a yarn setup workflow to use yarn commands 
https://github.com/marketplace/actions/yarn-setup

### CODE REVIEW

**Comment by Vithop** [comment]
kinda confused why my new workflow isn't working

**Comment by Khufu-I** [comment]
Why was this merged? There were no approvals and the tests were failing?

**Comment by Vithop** [comment]
Wait why was this reverted ? This is MY repo!!!!

**Comment by Khufu-I** [comment]
> Wait why was this reverted ? This is MY repo!!!!

The tests were consistently failing

**Pull request merged**
