### PR TITLE
Replace yarn.lock with package-lock

### PR DESCRIPTION
**Pull request by Khufu-I**
The default npm package manager and associated lock files are sufficient
for this project. Yarn has features and benefits over npm which won't be
significant in this project.

### CODE REVIEW

**Comment by Vithop** [comment]
yarn is more secure and faster than npm why would that be insignificant to this project?

**Comment by Vithop** [comment]
Yarn is also easier to use as it deals with version conflicts better.

**Comment by Khufu-I** [comment]
Yes all valid points. There are benefits to keeping things simple and using the default package manager. Since there aren’t too many dependencies npm and yarn performance ought to be similar. Also since there aren’t too many developers the version conflict shouldn’t be a big issue.

**Comment by Vithop** [comment]
I like yarn so I'm gonna veto this

**Pull request closed without merging**
